### ISSUE TITLE
Running on a repo without tags causes a `java.lang.StackOverflowError`

### ISSUE THREAD

**Issue by sschuberth** [dmfs/gver#91]
For testing, I've just applied the plugin to my root project, without doing any configuration in a `gver {}` closure. If Gradle configures the project, I'm running into

```
Cause: java.lang.StackOverflowError
    at org.eclipse.jgit.internal.storage.file.ObjectDirectory.openObject(ObjectDirectory.java:344)
    at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:132)
    at org.eclipse.jgit.revwalk.RevWalk.getCachedBytes(RevWalk.java:1130)
    at org.eclipse.jgit.revwalk.RevCommit.parseHeaders(RevCommit.java:126)
    at org.eclipse.jgit.revwalk.RevWalk.parseHeaders(RevWalk.java:1243)
    at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:1088)
    at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:996)
    at org.dmfs.gver.git.GitVersion.parsed(GitVersion.java:96)
    at org.dmfs.gver.git.GitVersion.readVersion(GitVersion.java:87)
    at org.dmfs.gver.git.GitVersion.lambda$readVersion$2(GitVersion.java:86)
    at org.dmfs.jems2.iterator.Mapped.next(Mapped.java:64)
    at org.dmfs.jems2.iterator.Mapped.next(Mapped.java:64)
    at org.dmfs.jems2.single.Reduced.value(Reduced.java:51)
    at org.dmfs.jems2.single.DelegatingSingle.value(DelegatingSingle.java:41)
    at org.dmfs.jems2.iterable.Sorted.iterator(Sorted.java:47)
    at org.dmfs.jems2.optional.First.lambda$new$0(First.java:52)
    at org.dmfs.jems2.single.Frozen.lambda$new$1(Frozen.java:35)
    at org.dmfs.jems2.single.Frozen.value(Frozen.java:45)
    at org.dmfs.jems2.optional.LazyDelegatingOptional.isPresent(LazyDelegatingOptional.java:47)
    at org.dmfs.jems2.iterator.Sieved.moveToNext(Sieved.java:86)
    at org.dmfs.jems2.iterator.Sieved.hasNext(Sieved.java:56)
    at org.dmfs.jems2.iterator.Mapped.hasNext(Mapped.java:57)
    at org.dmfs.jems2.optional.Next.lambda$new$0(Next.java:32)
    at org.dmfs.jems2.single.Frozen.lambda$new$1(Frozen.java:35)
    at org.dmfs.jems2.single.Frozen.value(Frozen.java:45)
    at org.dmfs.jems2.optional.LazyDelegatingOptional.isPresent(LazyDelegatingOptional.java:47)
    at org.dmfs.jems2.optional.LazyDelegatingOptional.isPresent(LazyDelegatingOptional.java:47)
    at org.dmfs.jems2.optional.DelegatingOptional.isPresent(DelegatingOptional.java:45)
    at org.dmfs.jems2.single.Backed.value(Backed.java:57)
    at org.dmfs.gver.git.GitVersion.readVersion(GitVersion.java:88)
    at org.dmfs.gver.git.GitVersion.lambda$readVersion$2(GitVersion.java:86)
    ...
```

This happens for a repo without any tags, and that just switched from arbitrary to conventional commits. To reproduce, run e.g. `./gradlew projects --stacktrace` on https://github.com/sschuberth/stan/tree/gver.

**Comment by dmfs** [comment]
Ah, got it. I guess the problem is that the recursive `readVersion` method doesn't find a valid version tag and thus goes deeper and deeper in the commit history until it blows the limit of the call stack size, which is probably somewhere between 5000 and 10000. With every recursion step having 30 method calls a history of 500 commits would require a stack that can take > 15000 calls.

I wonder what the best solution would be in that edge case. I guess the easiest one would be to manually add an "initial version" tag to of the recent commits. After all, projects like this typically already have a version number that was maintained manually or with another tool.
I'm not sure if it would make sense to determine the current version number based on the git history. At present, this would probably be something like `1.0.0-alpha.36`  or `0.1.0-alpha.536` because there were no releases in between and at present the plugin just increases the prerelease number if no release has been tagged. This change would require controverting the recursion to a loop.
What would be your expected behaviour (apart from not crashing, obviously)? Which version number would you expect to be generated for this project?

**Comment by sschuberth** [comment]
> With every recursion step having 30 method calls a history of 500 commits would require a stack that can take > 15000 calls.

Still surprising that the ~535 commits in my small project seem to cause problems.

> Which version number would you expect to be generated for this project?

AFAIK usually the first SemVer used in a (mature but previously unversioned) project would be 1.0.0. That is, if there's no tag, I would expected version 1.0.0 to be "calculated".

I don't know the details of the algorithm you use, but when I was trying the alternative https://github.com/jmongard/Git.SemVersioning.Gradle it had no such problems.

**Comment by dmfs** [comment]
the current implementation recursively traverses the commit tree upwards until it finds a version tag. I my projects that's typically just one commit away, usually less than 10 commits. Having no version tag for >> 100 commits just wasn't a use case before.
This is certainly fixable. Apparently recursion is not the right approach here. Even if I get the stack elements for one recursion cycle down, there will be a limit that might be hit in larger projects. So I guess I'll have to convert this to a loop instead, since tail-recursion is not an option in Java.

**Comment by sschuberth** [comment]
> tail-recursion is not an option in Java.

https://kotlinlang.org/docs/functions.html#tail-recursive-functions 😉 😆

**Comment by dmfs** [comment]
I can run `gitVersion` on your project now, the version number is almost as predicted:
```
$ ./gradlew gitVersion

> Task :gitVersion
0.0.1-alpha.536.20230916T090918Z-SNAPSHOT

BUILD SUCCESSFUL in 1s
10 actionable tasks: 1 executed, 9 up-to-date
[marten@localhost stan]$
```

I think that's almost correct. It should be `0.1.0-alpha.536.20230916T090918Z-SNAPSHOT` because you never start a project with a bug fix. I've addressed this in #93.
I think the `0` major complies best with [semver](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase)

**Comment by dmfs** [comment]
with version `0.26.1` this looks good now:
```
$ ./gradlew gitVersion

> Task :gitVersion
0.1.0-alpha.536.20230916T100802Z-SNAPSHOT

BUILD SUCCESSFUL in 6s
10 actionable tasks: 1 executed, 9 up-to-date
```

**Comment by sschuberth** [comment]
> 0.1.0-alpha.536.20230916T100802Z-SNAPSHOT

Interesting, I'm getting

```
$ ./gradlew gitVersion

> Task :gitVersion
0.1.0-alpha.535.20230916T103447Z-SNAPSHOT
```

(note the 536 vs 535 commits) although I have

```
$ git log --oneline | wc -l
536
```

Any idea what might cause this one-off?

**Comment by dmfs** [comment]
Yes, I can explain that.

You have 536 commits, but the pre-release counter starts at `0`, i.e. the first pre-release is just `alpha` (not `alpha.0`), the second one is `alpha.1`, ... the 536th one is `alpha.535`. That might be a bit counter intuitive, but probably not much of an issue. You can configure it to start at `alpha.1`  if you want to. `alpha`  is just the default.

A syntax example for this is in the readme:

```
gver {
    ...
    preReleases {
        on ~/main/ use { "beta" }
        on ~/feature\/(?<name>.*)/ use { "alpha-${group('name')}" }
        on ~/.*/ use { "SHAPSHOT" }
    }
}
```

I didn't amend the last commit when I changed the gver version, so the plugin generated another pre-release for the dirty repo. That explains why my pre-release version is higher.
